# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
