# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='precios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ppack', models.DecimalField(decimal_places=2, max_digits=5)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mayorista', models.DecimalField(decimal_places=2, max_digits=5)),
                ('minorista', models.DecimalField(decimal_places=2, max_digits=5)),
                ('agencia', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lista', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('linea', models.TextField()),
                ('codigo', models.TextField()),
                ('marca', models.TextField()),
                ('descripcion', models.TextField()),
                ('n_comercial', models.TextField()),
                ('imagen', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('u_medida', models.TextField()),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.almacen')),
            ],
        ),
    ]
