# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20170320_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='precios',
            name='p',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='producto.producto'),
        ),
    ]
