# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_precios_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='id_p',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='id_p', to='producto.producto'),
        ),
    ]
