# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_stock_id_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precios',
            name='p',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='id_p',
        ),
    ]
