# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20170320_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='almacen',
        ),
        migrations.AddField(
            model_name='stock',
            name='a_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
