# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        ('producto', '0006_auto_20170320_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='a_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='a_id',
            field=models.ManyToManyField(to='almacen.almacen'),
        ),
    ]
