# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 18:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0009_auto_20170323_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='precio',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='producto',
        ),
        migrations.DeleteModel(
            name='precio',
        ),
        migrations.DeleteModel(
            name='stock',
        ),
    ]
